language: node_js

node_js:
  - 7

services:
  - postgresql

before_script:
  - psql -U postgres -c 'create database test;'
  - psql -U postgres -d test -c 'create extension postgis'
  - psql -U postgres -d test -f test/table1.sql

script:
  - npm install -g yarn
  - yarn
  - npm test
